Repository boostcampwm-2024/iOS05-Heim, pull requests merged in 2024-12, with the labels that each got.

#117 [Fix] 일기 상세화면(1-1화면)
  Heim/Application/Application/Resource/Assets.xcassets/back.imageset/Contents.json
  Heim/Application/Application/Resource/Assets.xcassets/back.imageset/back.png
  Heim/Application/Application/Resource/Assets.xcassets/back.imageset/back@2x.png
  Heim/Application/Application/Resource/Assets.xcassets/back.imageset/back@3x.png
  Heim/Application/Application/Source/SceneDelegate.swift
  Heim/Presentation/Presentation/Common/TabBar/View/CustomTabBarViewController.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/Coordinator/DiaryDetailCoordinator.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailView.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailViewController.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
  Heim/Presentation/Presentation/Extension/Emotion+.swift
  Heim/Presentation/Presentation/Music/Coordinator/MusicMatchCoordinator.swift
  Heim/Presentation/Presentation/Music/View/MusicMatchViewController.swift
  Heim/Presentation/Presentation/Music/ViewModel/MusicMatchViewModel.swift
Labels: 🛠️ Fix

#126 [Feat] 통계 화면 기능 구현
  Heim/Application/Application/Source/SceneDelegate.swift
  Heim/DataModule/DataModule/Interface/Storage/DataStorageInterface.swift
  Heim/DataModule/DataModule/Repository/DefaultDiaryRepository.swift
  Heim/DataModule/DataModule/Repository/DefaultUserRepository.swift
  Heim/DataStorage/DataStorageModule/LocalStorage/DefaultLocalStorage.swift
  Heim/Domain/Domain/Entity/Emotion.swift
  Heim/Domain/Domain/Extension/Date+.swift
  Heim/Domain/Domain/Interface/Repository/DiaryRepository.swift
  Heim/Domain/Domain/Interface/Repository/UserRepository.swift
  Heim/Domain/Domain/UseCase/DiaryUseCase.swift
  Heim/Domain/Domain/UseCase/UserUseCase.swift
  Heim/Presentation/Presentation/Common/CommonLabel.swift
  Heim/Presentation/Presentation/Common/TabBar/Coordinator/TabBarCoordinator.swift
  Heim/Presentation/Presentation/Report/Coordinator/ReportCoordinator.swift
  Heim/Presentation/Presentation/Report/Model/Chart.swift
  Heim/Presentation/Presentation/Report/View/BarView.swift
  Heim/Presentation/Presentation/Report/View/GraphView.swift
  Heim/Presentation/Presentation/Report/View/HeimEmoji.swift
  Heim/Presentation/Presentation/Report/View/ReportCountView.swift
  Heim/Presentation/Presentation/Report/View/ReportView.swift
  Heim/Presentation/Presentation/Report/View/ReportViewController.swift
  Heim/Presentation/Presentation/Report/ViewModel/ReportViewModel.swift
Labels: 💫 Feat

#131 [Bug] AlertView 버그 수정
  Heim/Presentation/Presentation/Interface/AlertView.swift
Labels: 🐞 Bug

#119 [Fix] 음성 녹음(2번화면), 분석 결과(2-2화면)
  Heim/Presentation/Presentation/DiaryReplay/Manager/DiaryReplayManager.swift
  Heim/Presentation/Presentation/DiaryReplay/View/VisualizerView.swift
  Heim/Presentation/Presentation/Extension/UIImage+.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/View/AnalyzeResultView.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/View/EmotionAnalyzeViewController.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/ViewModel/EmotionAnalyzeViewModel.swift
  Heim/Presentation/Presentation/Record/RecordFeature/Manager/RecordManager.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordView.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordViewController.swift
  Heim/Presentation/Presentation/Record/RecordFeature/ViewModel/RecordViewModel.swift
Labels: 🛠️ Fix

#134 [Feat] 캘린더 셀 탭 이벤트 구현
  Heim/Presentation/Presentation/Home/View/CalendarView.swift
  Heim/Presentation/Presentation/Home/View/HomeViewController.swift
Labels: 💫 Feat

#122 [Feat] 음악추천화면과 MusicKit 연동
  Heim/DataModule/DataModule/Manager/AVPlayerManager.swift
  Heim/DataModule/DataModule/Repository/DefaultMusicRepository.swift
  Heim/Domain/Domain/Entity/Music/MusicTrack.swift
  Heim/Domain/Domain/Error/MusicError.swift
  Heim/Presentation/Presentation/Interface/Alertable.swift
  Heim/Presentation/Presentation/Music/Coordinator/MusicMatchCoordinator.swift
  Heim/Presentation/Presentation/Music/View/MusicMatchViewController.swift
  Heim/Presentation/Presentation/Music/View/MusicTableViewCell.swift
  Heim/Presentation/Presentation/Music/ViewModel/MusicMatchViewModel.swift
Labels: 💫 Feat

#124 [Fix] Modify the waveform to reactive
  Heim/Presentation/Presentation/DiaryReplay/Manager/DiaryReplayManager.swift
  Heim/Presentation/Presentation/DiaryReplay/View/DiaryReplayViewController.swift
  Heim/Presentation/Presentation/DiaryReplay/View/VisualizerView.swift
Labels: 🛠️ Fix

#137 [Feat] 사용자의 이름을 화면에 보여주기
  Heim/Presentation/Presentation/Detail/DiaryDetail/Coordinator/DiaryDetailCoordinator.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailViewController.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
  Heim/Presentation/Presentation/DiaryReplay/View/DiaryReplayView.swift
  Heim/Presentation/Presentation/DiaryReplay/View/DiaryReplayViewController.swift
  Heim/Presentation/Presentation/Extension/String+.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/Coordinator/AnalyzeResultCoordinator.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/View/AnalyzeResultView.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/View/AnalyzeResultViewController.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/ViewModel/AnalyzeResultViewModel.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/View/EmotionAnalyzeViewController.swift
Labels: 💫 Feat

#141 [Fix]캐시데이터 셀 삭제
  Heim/Presentation/Presentation/Setting/Model/SettingTableViewCellModel.swift
  Heim/Presentation/Presentation/Setting/View/SettingViewController.swift
Labels: 🛠️ Fix

#143 [Fix] Remove music recommendation buttons
  Heim/Presentation/Presentation/Detail/DiaryDetail/Coordinator/DiaryDetailCoordinator.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailView.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailViewController.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/Coordinator/AnalyzeResultCoordinator.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/View/AnalyzeResultView.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/View/AnalyzeResultViewController.swift
Labels: 🛠️ Fix

#146 [Feat] Error 발생 시 Alert를 띄우기
  Heim/DataModule/DataModule/Repository/DefaultSettingRepository.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailViewController.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
  Heim/Presentation/Presentation/Interface/Alertable.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/View/AnalyzeResultView.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/View/AnalyzeResultViewController.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/ViewModel/AnalyzeResultViewModel.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/Coordinator/EmotionAnalyzeCoordinator.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordViewController.swift
  Heim/Presentation/Presentation/Record/RecordFeature/ViewModel/RecordViewModel.swift
  Heim/Presentation/Presentation/Setting/View/SettingViewController.swift
  Heim/Presentation/Presentation/Setting/ViewModel/SettingViewModel.swift
Labels: 💫 Feat

#150 [Feat] Splash화면 추가
  Heim/Application/Application/Resource/Base.lproj/LaunchScreen.storyboard
  Heim/Application/Application/Source/AppDelegate.swift
Labels: 🎨 Design

#151 [Fix] Improvements for CoreML accuracy
  Heim/Presentation/Presentation/Interface/Alertable.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordViewController.swift
Labels: 🛠️ Fix

#148 [Fix] NameAlertView에 키보드 Notification 적용
  Heim/Presentation/Presentation/Common/Alert/NameAlertView.swift
Labels: 🛠️ Fix

#155 [Design] 홈 상단 여백 추가
  Heim/Presentation/Presentation/Home/View/HomeViewController.swift
  Heim/Presentation/Presentation/Setting/Coordinator/SettingCoordinator.swift
Labels: 🎨 Design

#156 [Fix] Add username to prompt
  Heim/Application/Application/Source/SceneDelegate.swift
  Heim/Domain/Domain/PromptGenerator/EmotionPromptGenerator.swift
  Heim/Domain/Domain/PromptGenerator/PromptGenerator.swift
  Heim/Domain/Domain/PromptGenerator/SummaryPromptGenerator.swift
  Heim/Domain/Domain/UseCase/GenerativeEmotionPromptUseCase.swift
  Heim/Domain/Domain/UseCase/GenerativeSummaryUseCase.swift
Labels: 🛠️ Fix

#158 [Bug] 탭바 탭을 선택할 때 마다 뷰를 새로 그리는 버그 수정
  Heim/Presentation/Presentation/Common/TabBar/Coordinator/TabBarCoordinator.swift
Labels: 🐞 Bug

#159 [Feat] 음성녹음 권한 설정 문제
  Heim/Presentation/Presentation/Interface/Alertable.swift
  Heim/Presentation/Presentation/Record/RecordFeature/Manager/RecordManager.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordViewController.swift
  Heim/Presentation/Presentation/Record/RecordFeature/ViewModel/RecordViewModel.swift
Labels: 💫 Feat

#161 [Fix] 일기 상세 뷰에서 감정에 맞는 이미지 선택
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailView.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailViewController.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
Labels: 🛠️ Fix

#164 [Feat] App Icon 적용, Application 모듈명 변경
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon-20@2x.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon-20@3x.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon-29@2x.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon-29@3x.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon-40@2x.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon-40@3x.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon-60@2x~car.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon-60@3x~car.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon-83.5@2x~ipad.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon114.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon128.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon136.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon192.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon76.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon@2x~ipad.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon~ios-marketing.png
  Heim/Application/Application/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Heim/Application/Heim.xcodeproj/project.pbxproj
  Heim/Application/Heim.xcodeproj/xcshareddata/xcschemes/Application.xcscheme
  Heim/Application/Heim.xcodeproj/xcshareddata/xcschemes/Heim.xcscheme
  Heim/Heim.xcworkspace/contents.xcworkspacedata
  Heim/Heim.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 💫 Feat

#165 [Fix] 통계 화면 일기 통계 텍스트 수정
  Heim/Presentation/Presentation/Report/View/ReportViewController.swift
Labels: 🛠️ Fix

#166 [Design] SplashView 추가
  Heim/Application/Application/Resource/Assets.xcassets/SpotifyLogo.imageset/Contents.json
  Heim/Application/Application/Resource/Assets.xcassets/SpotifyLogo.imageset/Spotify_icon.svg.png
  Heim/Application/Application/Resource/Assets.xcassets/splashRabbit.imageset/Contents.json
  Heim/Application/Application/Resource/Assets.xcassets/splashRabbit.imageset/SplashRabbit.png
  Heim/Application/Application/Resource/Assets.xcassets/splashRabbit.imageset/SplashRabbit2x.png
  Heim/Application/Application/Resource/Assets.xcassets/splashRabbit.imageset/SplashRabbit3x.png
  Heim/Application/Application/Resource/Base.lproj/LaunchScreen.storyboard
  Heim/Application/Application/Resource/splashView.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/spotifyFullLogo.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/spotifyFullLogo.imageset/spotify1.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/spotifyFullLogo.imageset/spotify2.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/spotifyFullLogo.imageset/spotify3.png
Labels: 🎨 Design

#168 [Fix] Handle analyze error
  Heim/Presentation/Presentation/Interface/Alertable.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/Coordinator/EmotionAnalyzeCoordinator.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/View/EmotionAnalyzeViewController.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/ViewModel/EmotionAnalyzeViewModel.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordViewController.swift
Labels: 🛠️ Fix, 🐞 Bug

#169 [Fix] Hotfix - control condition
  Heim/Presentation/Presentation/Record/EmotionAnalyze/View/EmotionAnalyzeViewController.swift
Labels: 🛠️ Fix, 🐞 Bug

#171 [Fix] Improvement prompt
  Heim/Domain/Domain/PromptGenerator/PromptGenerator.swift
Labels: 🛠️ Fix

#173 [Fix] 통계 화면 감정 설명 Label 텍스트 수정
  Heim/Presentation/Presentation/Report/View/ReportViewController.swift
Labels: 🛠️ Fix

#175 [Fix] Corrects AI not to mention names
  Heim/Application/Application/Source/SceneDelegate.swift
  Heim/Domain/Domain/PromptGenerator/EmotionPromptGenerator.swift
  Heim/Domain/Domain/PromptGenerator/PromptGenerator.swift
  Heim/Domain/Domain/PromptGenerator/SummaryPromptGenerator.swift
  Heim/Domain/Domain/UseCase/GenerativeEmotionPromptUseCase.swift
  Heim/Domain/Domain/UseCase/GenerativeSummaryUseCase.swift
Labels: 🛠️ Fix
