Repository boostcampwm-2024/iOS05-Heim, pull requests merged in 2024-11, with the labels that each got.

#7 [Chore] #6 Apply SwiftLint
  Heim/Application/Application.xcodeproj/project.pbxproj
  Heim/Application/swiftlint.yml
  Heim/Core/Core.xcodeproj/project.pbxproj
  Heim/DataModule/DataModule.xcodeproj/project.pbxproj
  Heim/DataStorage/DataStorage.xcodeproj/project.pbxproj
  Heim/Domain/Domain.xcodeproj/project.pbxproj
  Heim/Heim.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Heim/NetworkModule/NetworkModule.xcodeproj/project.pbxproj
  Heim/Presentation/Presentation.xcodeproj/project.pbxproj
Labels: 📦 Chore

#10 [Design] #8 Add Common TextArea
  Heim/Presentation/Presentation/Common/CommonTextAreaView.swift
Labels: 🎨 Design

#16 [Feat] #2 CustomTabBar
  Heim/Presentation/Presentation/Common/TabBar/CustomTabBarView.swift
  Heim/Presentation/Presentation/Common/TabBar/CustomTabBarViewController.swift
  Heim/Presentation/Presentation/Common/TabBar/CustomTabBarViewModel.swift
Labels: 💫 Feat, ♻️ Refactor, 🎨 Design

#12 [Feat] #1 HomeUI구현
  Heim/Presentation/Presentation/Home/CalendarCell.swift
  Heim/Presentation/Presentation/Home/CalendarView.swift
  Heim/Presentation/Presentation/Home/DayofWeek.swift
  Heim/Presentation/Presentation/Home/HomeViewController.swift
Labels: 🎨 Design

#15 [Feat] #9 설정 화면 구현
  Heim/Application/Application.xcodeproj/project.pbxproj
  Heim/Application/Application/Resource/Assets.xcassets/splashRabbit.imageset/Contents.json
  Heim/Application/Application/Resource/Assets.xcassets/splashRabbit.imageset/SplashRabbit.png
  Heim/Application/Application/Resource/Assets.xcassets/splashRabbit.imageset/SplashRabbit2x.png
  Heim/Application/Application/Resource/Assets.xcassets/splashRabbit.imageset/SplashRabbit3x.png
  Heim/Application/Application/Source/SceneDelegate.swift
  Heim/Core/Core/DIContainer/DIContainer.swift
  Heim/DataModule/DataModule/Repository/DefaultSettingRepository.swift
  Heim/Domain/Domain/Interface/Repository/SettingRepository.swift
  Heim/Domain/Domain/UseCase/SettingUseCase.swift
  Heim/Presentation/Presentation/Common/Assets.xcassets/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/backIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/backIcon.imageset/back.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/backIcon.imageset/back@2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/backIcon.imageset/back@3x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/background.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/background.imageset/background.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/background.imageset/background2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/background.imageset/background3x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/cloudIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/cloudIcon.imageset/u_cloud-upload.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/cloudIcon.imageset/u_cloud-upload@2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/cloudIcon.imageset/u_cloud-upload@3x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/helpIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/helpIcon.imageset/fi_help-circle.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/helpIcon.imageset/fi_help-circle@2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/helpIcon.imageset/fi_help-circle@3x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/infoIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/infoIcon.imageset/u_info-circle.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/infoIcon.imageset/u_info-circle@2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/infoIcon.imageset/u_info-circle@3x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/smileIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/smileIcon.imageset/u_smile.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/smileIcon.imageset/u_smile@2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/smileIcon.imageset/u_smile@3x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/trashIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/trashIcon.imageset/fi_trash-2.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/trashIcon.imageset/fi_trash-2@2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/trashIcon.imageset/fi_trash-2@3x.png
  Heim/Presentation/Presentation/Common/CommonLabel.swift
  Heim/Presentation/Presentation/Extension/UIColor+.swift
  Heim/Presentation/Presentation/Extension/UITableView+.swift
  Heim/Presentation/Presentation/Interface/BaseViewController.swift
  Heim/Presentation/Presentation/Setting/Coordinator/SettingCoordinator.swift
  Heim/Presentation/Presentation/Setting/View/SettingTableViewCell.swift
  Heim/Presentation/Presentation/Setting/View/SettingViewController.swift
  Heim/Presentation/Presentation/Setting/ViewModel/SettingViewModel.swift
Labels: 💫 Feat, 🎨 Design

#25 [Feat] Implement NetworkModule
  Heim/DataModule/DataModule/Interface/NetworkProvider/HTTPMethod.swift
  Heim/DataModule/DataModule/Interface/NetworkProvider/NetworkProvider.swift
  Heim/DataModule/DataModule/Interface/NetworkProvider/NetworkProviderTmp.swift
  Heim/DataModule/DataModule/Interface/NetworkProvider/RequestTarget.swift
  Heim/NetworkModule/NetworkModule/Extension/RequestTarget+.swift
  Heim/NetworkModule/NetworkModule/Extension/URLRequest+.swift
  Heim/NetworkModule/NetworkModule/NetworkProvider/DefaultNetworkProvider.swift
  Heim/NetworkModule/NetworkModule/NetworkProvider/tmp.swift
Labels: 💫 Feat

#23 [Refactor] HomeUI 리팩토링
  Heim/Presentation/Presentation/Extension/UIColor+.swift
  Heim/Presentation/Presentation/Home/CalendarCell.swift
  Heim/Presentation/Presentation/Home/CalendarView.swift
  Heim/Presentation/Presentation/Home/HomeViewController.swift
Labels: ♻️ Refactor, 🎨 Design

#22 [Refactor] 설정 화면 TableView DataSource 로직 개선
  Heim/Presentation/Presentation/Extension/UIImage+.swift
  Heim/Presentation/Presentation/Setting/Model/SettingTableViewCellModel.swift
  Heim/Presentation/Presentation/Setting/View/SettingViewController.swift
Labels: ♻️ Refactor

#24 [Feat] 팝업 기능 구현
  Heim/Presentation/Presentation/Common/Alert/AlertViewController.swift
  Heim/Presentation/Presentation/Common/Alert/CommonAlertView.swift
  Heim/Presentation/Presentation/Common/CommonLabel.swift
  Heim/Presentation/Presentation/Common/CommonRectangleButton.swift
  Heim/Presentation/Presentation/Extension/UIColor+.swift
  Heim/Presentation/Presentation/Extension/UIView+.swift
  Heim/Presentation/Presentation/Interface/Alertable.swift
Labels: 💫 Feat, 🎨 Design

#35 [Feat] Implement CoreML-related feature
  Heim/Domain/Domain/Entity/Diary.swift
  Heim/Domain/Domain/Entity/Emotion.swift
  Heim/Domain/Domain/Entity/EmotionReport.swift
  Heim/Domain/Domain/Entity/EntityTmp.swift
  Heim/Domain/Domain/Entity/Summary.swift
  Heim/Domain/Domain/Entity/Voice.swift
  Heim/Domain/Domain/MLModel/EmotionClassifier.mlmodel
  Heim/Domain/Domain/UseCase/EmotionClassifyUseCase.swift
Labels: 💫 Feat

#29 [Feat] 음성 녹음 기능 구현
  Heim/Application/Application.xcodeproj/project.pbxproj
  Heim/Presentation/Presentation/Common/Assets.xcassets/arrowClockwise.symbolset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/arrowClockwise.symbolset/arrow.clockwise.svg
  Heim/Presentation/Presentation/Common/Assets.xcassets/playFill.symbolset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/playFill.symbolset/play.fill.svg
  Heim/Presentation/Presentation/Common/Assets.xcassets/recordRabbit.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/recordRabbit.imageset/SplashRabbit.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/recordRabbit.imageset/SplashRabbit2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/recordRabbit.imageset/SplashRabbit3x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/stopFill.symbolset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/stopFill.symbolset/stop.fill.svg
  Heim/Presentation/Presentation/Common/Assets.xcassets/xmark.symbolset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/xmark.symbolset/xmark.svg
  Heim/Presentation/Presentation/Extension/UIApplication+.swift
  Heim/Presentation/Presentation/Record/RecordFeature/Coordinator/RecordCoordinator.swift
  Heim/Presentation/Presentation/Record/RecordFeature/Manager/RecordManager.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordView.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordViewController.swift
  Heim/Presentation/Presentation/Record/RecordFeature/ViewModel/RecordViewModel.swift
Labels: 💫 Feat, ♻️ Refactor, 🎨 Design

#45 [Test] MLModel 적용, 감정 분석 UseCase 테스트
  Heim/Domain/Domain/Entity/Emotion.swift
  Heim/Domain/Domain/MLModel/EmotionClassifier.mlmodel
  Heim/Domain/Domain/UseCase/EmotionClassifyUseCase.swift
  Heim/Domain/DomainTests/DomainTests.swift
  Heim/Domain/DomainTests/EmotionClassfyUseCaseTests.swift
Labels: 📐 Test

#46 [Feat] DataStorage 구현
  Heim/DataModule/DataModule/Interface/Storage/DataStorageInterface.swift
  Heim/DataModule/DataModule/Interface/Storage/StorageTmp.swift
  Heim/DataModule/DataModule/Repository/DefaultDiaryRepository.swift
  Heim/DataStorage/DataStorage/LocalStorage/DefaultLocalStorage.swift
  Heim/DataStorage/DataStorage/LocalStorage/LocalStorageTmp.swift
  Heim/Domain/Domain/Entity/Diary.swift
  Heim/Domain/Domain/Entity/EmotionReport.swift
  Heim/Domain/Domain/Entity/Summary.swift
  Heim/Domain/Domain/Entity/Voice.swift
  Heim/Domain/Domain/Error/StorageError.swift
  Heim/Domain/Domain/Interface/Repository/DiaryRepository.swift
  Heim/Domain/Domain/UseCase/DiaryUseCase.swift
Labels: 💫 Feat

#48 [Feat] 일기 상세 화면(1-1) 구현
  Heim/Presentation/Presentation/Detail/DiaryDetail/Coordinator/DiaryDetailCoordinator.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailView.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailViewController.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordView.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordViewController.swift
  Heim/Presentation/Presentation/Record/RecordFeature/ViewModel/RecordViewModel.swift
Labels: 💫 Feat, 🎨 Design

#51 [Feat] Record Error Handling
  Heim/Presentation/Presentation/Record/RecordFeature/Manager/RecordManager.swift
  Heim/Presentation/Presentation/Record/RecordFeature/ViewModel/RecordViewModel.swift
Labels: 💫 Feat

#39 [Feat] Implementing Gemini-Related Features
  Heim/DataModule/DataModule.xcodeproj/project.pbxproj
  Heim/DataModule/DataModule/API/GeminiAPI.swift
  Heim/DataModule/DataModule/API/GeminiEnvironment.swift
  Heim/DataModule/DataModule/Info.plist
  Heim/DataModule/DataModule/Repository/GeminiGenerativeAIRepository.swift
  Heim/DataModule/DataModule/ResponseDTO/GeminiGenerateResponseDTO.swift
  Heim/Domain/Domain/Interface/Repository/GenerativeAIRepository.swift
  Heim/Domain/Domain/Interface/Repository/RepositoryTmp.swift
  Heim/Domain/Domain/PromptGenerator/EmotionPromptGenerator.swift
  Heim/Domain/Domain/PromptGenerator/PromptGenerating.swift
  Heim/Domain/Domain/PromptGenerator/SummaryPromptGenerator.swift
  Heim/Domain/Domain/RequestDTO/GeminiGenerateRequestDTO.swift
  Heim/NetworkModule/NetworkModule/Extension/RequestTarget+.swift
  Heim/NetworkModule/NetworkModule/NetworkProvider/DefaultNetworkProvider.swift
Labels: 💫 Feat, 🛠️ Fix, ♻️ Refactor

#61 [Fix] Data 모듈 Info.plist 파일명 변경
  Heim/DataModule/DataModule.xcodeproj/project.pbxproj
  Heim/DataModule/DataModule/DataModuleInfo.plist
Labels: 🛠️ Fix

#72 [Fix] Emotion 엔티티 변경 사항으로 인한 컴파일 에러 수정
  Heim/Domain/Domain/PromptGenerator/EmotionPromptGenerator.swift
Labels: 🛠️ Fix

#58 [Feat] 감정 분석(2-1) 화면 구현
  Heim/Domain/Domain/UseCase/EmotionClassifyUseCase.swift
  Heim/Presentation/Presentation/Extension/UIColor+.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/Coordinator/EmotionAnalyzeCoordinator.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/View/EmotionAnalyzeView.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/View/EmotionAnalyzeViewController.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/ViewModel/EmotionAnalyzeViewModel.swift
Labels: 💫 Feat, 🎨 Design

#55 [Feat] 음성 녹음 데이터를 다음화면으로 전달
  Heim/Presentation/Presentation/Record/RecordFeature/Coordinator/RecordCoordinator.swift
  Heim/Presentation/Presentation/Record/RecordFeature/Manager/RecordManager.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordViewController.swift
  Heim/Presentation/Presentation/Record/RecordFeature/ViewModel/RecordViewModel.swift
Labels: 💫 Feat

#63 [Feat] HomeCoordinator 구현, 화면 전환 기능 구현
  Heim/Presentation/Presentation/Common/Assets.xcassets/settingIcon.imageset/setting.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/settingIcon.imageset/setting@2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/settingIcon.imageset/setting@3x.png
  Heim/Presentation/Presentation/Home/Coordinator/HomeCoordinator.swift
  Heim/Presentation/Presentation/Home/HomeViewController.swift
  Heim/Presentation/Presentation/Home/View/CalendarCell.swift
  Heim/Presentation/Presentation/Home/View/CalendarView.swift
  Heim/Presentation/Presentation/Home/View/DayofWeek.swift
  Heim/Presentation/Presentation/Home/View/HomeViewController.swift
  Heim/Presentation/Presentation/Interface/BaseViewController.swift
  Heim/Presentation/Presentation/Interface/ViewModel.swift
Labels: 💫 Feat

#65 [Feat] TabBar Coordinator 구현
  Heim/Presentation/Presentation/Common/TabBar/Coordinator/TabBarCoordinator.swift
  Heim/Presentation/Presentation/Interface/Coordinator.swift
  Heim/Presentation/Presentation/Record/RecordFeature/Coordinator/RecordCoordinator.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordViewController.swift
  Heim/Presentation/Presentation/Record/RecordFeature/ViewModel/RecordViewModel.swift
Labels: 💫 Feat

#67 [Refactor] TabBar Coordinator 연결, 구조 개선
  Heim/Application/Application/Source/SceneDelegate.swift
  Heim/Presentation/Presentation/Common/Assets.xcassets/calendarIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/calendarIcon.imageset/calendar.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/calendarIcon.imageset/calendar@2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/calendarIcon.imageset/calendar@3x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/micIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/micIcon.imageset/micIcon.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/micIcon.imageset/micIcon@2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/micIcon.imageset/micIcon@3x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/reportIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/reportIcon.imageset/report.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/reportIcon.imageset/report@2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/reportIcon.imageset/report@3x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/settingIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/TabBar/CustomTabBarView.swift
  Heim/Presentation/Presentation/Common/TabBar/CustomTabBarViewController.swift
  Heim/Presentation/Presentation/Common/TabBar/CustomTabBarViewModel.swift
  Heim/Presentation/Presentation/Common/TabBar/Model/CustomTabBarModel.swift
  Heim/Presentation/Presentation/Common/TabBar/View/CustomTabBarView.swift
  Heim/Presentation/Presentation/Common/TabBar/View/CustomTabBarViewController.swift
  Heim/Presentation/Presentation/Common/TabBar/View/CustomTabButton.swift
Labels: 💫 Feat, ♻️ Refactor

#59 [Design] 통계화면 구현
  Heim/Application/Application/Source/SceneDelegate.swift
  Heim/DataModule/DataModule/Repository/DefaultReportRepository.swift
  Heim/Domain/Domain/Interface/Repository/ReportRepository.swift
  Heim/Domain/Domain/UseCase/ReportUseCase.swift
  Heim/Presentation/Presentation/Common/Assets.xcassets/disgustIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/disgustIcon.imageset/disgust.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/disgustIcon.imageset/disgust2.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/disgustIcon.imageset/disgust3.png
  Heim/Presentation/Presentation/Report/Coordinator/ReportCoordinator.swift
  Heim/Presentation/Presentation/Report/Model/Chart.swift
  Heim/Presentation/Presentation/Report/View/BarView.swift
  Heim/Presentation/Presentation/Report/View/GraphView.swift
  Heim/Presentation/Presentation/Report/View/HeimEmoji.swift
  Heim/Presentation/Presentation/Report/View/ReportCountView.swift
  Heim/Presentation/Presentation/Report/View/ReportView.swift
  Heim/Presentation/Presentation/Report/View/ReportViewController.swift
  Heim/Presentation/Presentation/Report/ViewModel/ReportViewModel.swift
Labels: 💫 Feat, 🎨 Design

#77 [Feat] 음성 녹음 Flow의 Animation 구현
  Heim/Application/Application.xcodeproj/project.pbxproj
  Heim/Heim.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Heim/Presentation/Presentation.xcodeproj/project.pbxproj
  Heim/Presentation/Presentation/Common/Lottie/microphone.json
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordView.swift
Labels: 💫 Feat, 🎨 Design, 📦 Chore

#74 [Feat] 일기 상세(1-1) 삭제 기능 구현
  Heim/Presentation/Presentation/Common/Alert/AlertViewController.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/Coordinator/DiaryDetailCoordinator.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailViewController.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
Labels: 💫 Feat

#78 [Feat] 음악 추천 뷰 구현
  Heim/Presentation/Presentation/Extension/UIColor+.swift
  Heim/Presentation/Presentation/Music/Coordinator/MusicMatchCoordinator.swift
  Heim/Presentation/Presentation/Music/View/MusicMatchViewController.swift
  Heim/Presentation/Presentation/Music/View/MusicTableViewCell.swift
Labels: 💫 Feat, 🎨 Design

#75 [Feat] Implement Spotify Recommendation API
  Heim/DataModule/DataModule/API/SpotifyAPI.swift
  Heim/DataModule/DataModule/API/SpotifyOAuthAPI.swift
  Heim/DataModule/DataModule/Repository/DefaultSpotifyRepository.swift
  Heim/DataModule/DataModule/ResponseDTO/SpotifyRecommendResponseDTO.swift
  Heim/Domain/Domain/Entity/Seed.swift
  Heim/Domain/Domain/Entity/SpotifyTrack.swift
  Heim/Domain/Domain/Entity/Track.swift
  Heim/Domain/Domain/Error/EmotionError.swift
  Heim/Domain/Domain/Interface/Repository/SpotifyRepository.swift
  Heim/Domain/Domain/RequestDTO/DictionaryRepresentable.swift
  Heim/Domain/Domain/RequestDTO/SpotifyAuthorizeRequestDTO.swift
  Heim/Domain/Domain/RequestDTO/SpotifyRecommendRequestDTO.swift
  Heim/Domain/Domain/RequestDTO/SpotifyRecommendRequestDTOFactory.swift
  Heim/Domain/Domain/UseCase/MusicUseCase.swift
Labels: 💫 Feat, ♻️ Refactor

#85 [Feat] 설정 화면 세부 기능 구현
  Heim/DataModule/DataModule/Interface/Storage/DataStorageInterface.swift
  Heim/DataModule/DataModule/Repository/DefaultSettingRepository.swift
  Heim/DataStorage/DataStorage/LocalStorage/DefaultLocalStorage.swift
  Heim/Presentation/Presentation/Interface/Alertable.swift
  Heim/Presentation/Presentation/Setting/Coordinator/SettingCoordinator.swift
  Heim/Presentation/Presentation/Setting/View/SettingViewController.swift
  Heim/Presentation/Presentation/Setting/ViewModel/SettingViewModel.swift
Labels: 💫 Feat

#90 [Feat] Implement music play feature via Spotify API
  Heim/Application/Application.xcodeproj/project.pbxproj
  Heim/Application/Application/Resource/Info.plist
  Heim/DataModule/DataModule/Manager/AVPlayerManager.swift
  Heim/DataModule/DataModule/Repository/DefaultMusicRepository.swift
  Heim/Domain/Domain/Entity/Track.swift
  Heim/Domain/Domain/Error/MusicError.swift
  Heim/Domain/Domain/Interface/Repository/MusicRepository.swift
  Heim/Domain/Domain/RequestDTO/DictionaryRepresentable.swift
  Heim/Domain/Domain/UseCase/MusicUseCase.swift
  Heim/Presentation/Presentation/Music/View/SpotifyLoginView.swift
  Heim/Presentation/Presentation/Music/ViewModel/SpotifyLoginViewModel.swift
Labels: 💫 Feat, 🛠️ Fix

#86 [Refactor] 통계화면 리팩토링
  Heim/Application/Application/Source/SceneDelegate.swift
  Heim/Presentation/Presentation/Common/Assets.xcassets/angryIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/angryIcon.imageset/angry1.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/angryIcon.imageset/angry2.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/angryIcon.imageset/angry3.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/fearIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/fearIcon.imageset/fear1.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/fearIcon.imageset/fear2.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/fearIcon.imageset/fear3.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/happyIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/happyIcon.imageset/happiness1.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/happyIcon.imageset/happiness2.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/happyIcon.imageset/happiness3.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/neutralIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/neutralIcon.imageset/neutral1.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/neutralIcon.imageset/neutral2.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/neutralIcon.imageset/neutral3.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/sadIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/sadIcon.imageset/sadness.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/sadIcon.imageset/sadness2.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/sadIcon.imageset/sadness3.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/surpriseIcon.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/surpriseIcon.imageset/surprise1.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/surpriseIcon.imageset/surprise2.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/surpriseIcon.imageset/surprise3.png
  Heim/Presentation/Presentation/Extension/UIColor+.swift
  Heim/Presentation/Presentation/Report/View/BarView.swift
  Heim/Presentation/Presentation/Report/View/GraphView.swift
  Heim/Presentation/Presentation/Report/View/HeimEmoji.swift
  Heim/Presentation/Presentation/Report/View/ReportCountView.swift
  Heim/Presentation/Presentation/Report/View/ReportView.swift
Labels: ♻️ Refactor

#79 [Feat] 이름 설정 Alert 팝업 구현, 기존 Alert 팝업 확장성 개선
  Heim/Presentation/Presentation/Common/Alert/AlertViewController.swift
  Heim/Presentation/Presentation/Common/Alert/CommonAlertView.swift
  Heim/Presentation/Presentation/Common/Alert/NameAlertView.swift
  Heim/Presentation/Presentation/Interface/AlertView.swift
  Heim/Presentation/Presentation/Interface/Alertable.swift
  Heim/Presentation/Presentation/Setting/View/SettingViewController.swift
Labels: 💫 Feat

#93 [Design] 음악추천 뷰 리팩토링
  Heim/Presentation/Presentation/Music/Coordinator/MusicMatchCoordinator.swift
  Heim/Presentation/Presentation/Music/View/MusicMatchViewController.swift
  Heim/Presentation/Presentation/Music/ViewModel/MusicMatchViewModel.swift
Labels: 💫 Feat, 🎨 Design

#102 [Feat] 화면 연결 (음성 녹음, 2-1, 2-2)
  Heim/Application/Application/Source/SceneDelegate.swift
  Heim/Presentation/Presentation/Common/TabBar/Coordinator/TabBarCoordinator.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/Coordinator/AnalyzeResultCoordinator.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/View/AnalyzeResultViewController.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/Coordinator/EmotionAnalyzeCoordinator.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/View/EmotionAnalyzeViewController.swift
  Heim/Presentation/Presentation/Record/RecordFeature/Coordinator/RecordCoordinator.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordViewController.swift
  Heim/Presentation/Presentation/Record/RecordFeature/ViewModel/RecordViewModel.swift
Labels: 💫 Feat

#95 [Refactor/Fix] Enhancement Spotify & MusicKit features
  Heim/DataModule/DataModule/API/SpotifyAPI.swift
  Heim/DataModule/DataModule/API/SpotifyEnvironment.swift
  Heim/DataModule/DataModule/API/SpotifyOAuthAPI.swift
  Heim/DataModule/DataModule/DTO/Request/GeminiGenerateRequestDTO.swift
  Heim/DataModule/DataModule/DTO/Request/SpotifyAccessTokenRequestDTO.swift
  Heim/DataModule/DataModule/DTO/Request/SpotifyAuthorizeRequestDTO.swift
  Heim/DataModule/DataModule/DTO/Request/SpotifyRecommendRequestDTO.swift
  Heim/DataModule/DataModule/DTO/Request/SpotifyRefreshTokenRequestDTO.swift
  Heim/DataModule/DataModule/DTO/Response/GeminiGenerateResponseDTO.swift
  Heim/DataModule/DataModule/DTO/Response/SpotifyAccessTokenResponseDTO.swift
  Heim/DataModule/DataModule/DTO/Response/SpotifyRecommendResponseDTO.swift
  Heim/DataModule/DataModule/DTO/Util/DictionaryRepresentable.swift
  Heim/DataModule/DataModule/DTO/Util/SpotifyRecommendRequestDTOFactory.swift
  Heim/DataModule/DataModule/Interface/Storage/KeychainStorage.swift
  Heim/DataModule/DataModule/Interface/Storage/TokenStorage.swift
  Heim/DataModule/DataModule/Manager/TokenManager.swift
  Heim/DataModule/DataModule/Repository/DefaultSpotifyOAuthRepository.swift
  Heim/DataModule/DataModule/Repository/DefaultSpotifyRepository.swift
  Heim/DataStorage/DataStorage/TokenStorage/DefaultKeychainStorage.swift
  Heim/DataStorage/DataStorage/TokenStorage/KeychainTokenStorage.swift
  Heim/Domain/Domain/Entity/Music/MusicTrack.swift
  Heim/Domain/Domain/Entity/Music/Seed.swift
  Heim/Domain/Domain/Entity/Music/SpotifyTrack.swift
  Heim/Domain/Domain/Error/TokenError.swift
  Heim/Domain/Domain/Interface/Repository/SpotifyOAuthRepository.swift
  Heim/Domain/Domain/Interface/Repository/SpotifyRepository.swift
  Heim/Domain/Domain/UseCase/MusicUseCase.swift
  Heim/Domain/Domain/UseCase/SpotifyOAuthUseCase.swift
  Heim/NetworkModule/NetworkModule/Extension/RequestTarget+.swift
  Heim/NetworkModule/NetworkModule/Extension/URLRequest+.swift
  Heim/NetworkModule/NetworkModule/NetworkProvider/DefaultNetworkProvider.swift
  Heim/NetworkModule/NetworkModule/NetworkProvider/OAuthNetworkProvider.swift
Labels: 🛠️ Fix, ♻️ Refactor

#101 [Design] Add Reply View
  Heim/Presentation/Presentation/Detail/DiaryDetail/Coordinator/DiaryDetailCoordinator.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailViewController.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
  Heim/Presentation/Presentation/Reply/View/ReplyViewController.swift
Labels: 🎨 Design

#104 [Feat] 홈 화면 미구현 기능 구현, DataStorage 로직 수정 등
  Heim/Application/Application.xcodeproj/project.pbxproj
  Heim/Application/Application/Source/SceneDelegate.swift
  Heim/DataModule/DataModule/Interface/Storage/DataStorageInterface.swift
  Heim/DataModule/DataModule/Repository/DefaultDiaryRepository.swift
  Heim/DataModule/DataModule/Repository/DefaultSettingRepository.swift
  Heim/DataStorage/DataStorage.xcodeproj/project.pbxproj
  Heim/DataStorage/DataStorage/LocalStorage/DefaultLocalStorage.swift
  Heim/DataStorage/DataStorageModule.xcodeproj/project.pbxproj
  Heim/Domain/Domain/Entity/CalendarDate.swift
  Heim/Domain/Domain/Entity/Diary.swift
  Heim/Domain/Domain/Entity/Emotion.swift
  Heim/Domain/Domain/Entity/EmotionReport.swift
  Heim/Domain/Domain/Entity/Summary.swift
  Heim/Domain/Domain/Entity/Voice.swift
  Heim/Domain/Domain/Error/StorageError.swift
  Heim/Domain/Domain/Interface/Repository/DiaryRepository.swift
  Heim/Domain/Domain/UseCase/DiaryUseCase.swift
  Heim/Heim.xcworkspace/contents.xcworkspacedata
  Heim/Presentation/Presentation/Common/Assets.xcassets/chevronLeft.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/chevronLeft.imageset/chevronLeft.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/chevronLeft.imageset/chevronLeft@2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/chevronLeft.imageset/chevronLeft@3x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/chevronRight.imageset/Contents.json
  Heim/Presentation/Presentation/Common/Assets.xcassets/chevronRight.imageset/chevronRight.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/chevronRight.imageset/chevronRight@2x.png
  Heim/Presentation/Presentation/Common/Assets.xcassets/chevronRight.imageset/chevronRight@3x.png
  Heim/Presentation/Presentation/Common/TabBar/Coordinator/TabBarCoordinator.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
  Heim/Presentation/Presentation/Extension/Date+.swift
  Heim/Presentation/Presentation/Extension/UIApplication+.swift
  Heim/Presentation/Presentation/Extension/UICollectionView+.swift
  Heim/Presentation/Presentation/Extension/UIColor+.swift
  Heim/Presentation/Presentation/Home/Coordinator/HomeCoordinator.swift
  Heim/Presentation/Presentation/Home/Model/CalendarCellModel.swift
  Heim/Presentation/Presentation/Home/View/CalendarCell.swift
  Heim/Presentation/Presentation/Home/View/CalendarView.swift
  Heim/Presentation/Presentation/Home/View/HomeViewController.swift
  Heim/Presentation/Presentation/Home/ViewModel/HomeViewModel.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/ViewModel/AnalyzeResultViewModel.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/ViewModel/EmotionAnalyzeViewModel.swift
Labels: 💫 Feat

#105 [Fix] Merge Conflict 수정
  Heim/DataStorage/DataStorageModule.xcodeproj/project.pbxproj
  Heim/DataStorage/DataStorageModule/CloudStorage/CloudStorageTmp.swift
  Heim/DataStorage/DataStorageModule/LocalStorage/DefaultLocalStorage.swift
  Heim/DataStorage/DataStorageModule/TokenStorage/DefaultKeychainStorage.swift
  Heim/DataStorage/DataStorageModuleTests/DataStorageTests.swift
  Heim/Presentation/Presentation/Setting/View/SettingViewController.swift
Labels: 🛠️ Fix

#106 [Design] Design Record replay view
  Heim/Presentation/Presentation/Detail/DiaryDetail/Coordinator/DiaryDetailCoordinator.swift
  Heim/Presentation/Presentation/DiaryReplay/Manager/DiaryReplayManager.swift
  Heim/Presentation/Presentation/DiaryReplay/View/DiaryReplayView.swift
  Heim/Presentation/Presentation/DiaryReplay/View/DiaryReplayViewController.swift
  Heim/Presentation/Presentation/DiaryReplay/View/VisualizerView.swift
  Heim/Presentation/Presentation/DiaryReplay/ViewModel/DiaryReplayViewModel.swift
Labels: 🎨 Design

#109 [Feat] Connect All Views
  Heim/Application/Application/Source/SceneDelegate.swift
  Heim/DataModule/DataModule.xcodeproj/project.pbxproj
  Heim/DataModule/DataModule/Interface/NetworkProvider/OAuthNetworkProvider.swift
  Heim/DataModule/DataModule/Repository/DefaultReportRepository.swift
  Heim/Domain/Domain.xcodeproj/project.pbxproj
  Heim/Domain/Domain/UseCase/ReportUseCase.swift
  Heim/Domain/Domain/UseCase/UseCaseTmp.swift
  Heim/NetworkModule/NetworkModule/NetworkProvider/DefaultOAuthNetworkProvider.swift
  Heim/Presentation/Presentation/Common/TabBar/Coordinator/TabBarCoordinator.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/Coordinator/DiaryDetailCoordinator.swift
  Heim/Presentation/Presentation/Detail/DiaryDetail/View/DiaryDetailViewController.swift
  Heim/Presentation/Presentation/Home/View/CalendarView.swift
  Heim/Presentation/Presentation/Home/View/HomeViewController.swift
  Heim/Presentation/Presentation/Music/Coordinator/MusicMatchCoordinator.swift
  Heim/Presentation/Presentation/Music/View/MusicMatchViewController.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/Coordinator/AnalyzeResultCoordinator.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/View/AnalyzeResultView.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/View/AnalyzeResultViewController.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/ViewModel/AnalyzeResultViewModel.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/View/EmotionAnalyzeViewController.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/ViewModel/EmotionAnalyzeViewModel.swift
  Heim/Presentation/Presentation/Record/RecordFeature/View/RecordViewController.swift
  Heim/Presentation/Presentation/Report/Coordinator/ReportCoordinator.swift
  Heim/Presentation/Presentation/Report/View/ReportViewController.swift
  Heim/Presentation/Presentation/Report/ViewModel/ReportViewModel.swift
  Heim/Presentation/Presentation/Setting/Model/SettingTableViewCellModel.swift
  Heim/Presentation/Presentation/Setting/View/SettingViewController.swift
Labels: 💫 Feat, 🛠️ Fix, ♻️ Refactor, 🧹 Style

#111 [Fix] Enhancement VisualizerView
  Heim/Presentation/Presentation/DiaryReplay/Manager/DiaryReplayManager.swift
  Heim/Presentation/Presentation/DiaryReplay/View/DiaryReplayViewController.swift
  Heim/Presentation/Presentation/DiaryReplay/View/VisualizerView.swift
  Heim/Presentation/Presentation/DiaryReplay/ViewModel/DiaryReplayViewModel.swift
Labels: 🛠️ Fix

#112 [Feat] GEMINI 기능 추가
  Heim/Application/Application/Source/SceneDelegate.swift
  Heim/Domain/Domain/PromptGenerator/EmotionPromptGenerator.swift
  Heim/Domain/Domain/PromptGenerator/SummaryPromptGenerator.swift
  Heim/Domain/Domain/UseCase/GenerativeEmotionPromptUseCase.swift
  Heim/Domain/Domain/UseCase/GenerativeSummaryUseCase.swift
  Heim/Presentation/Presentation/Record/AnalyzeResult/View/AnalyzeResultView.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/Coordinator/EmotionAnalyzeCoordinator.swift
  Heim/Presentation/Presentation/Record/EmotionAnalyze/ViewModel/EmotionAnalyzeViewModel.swift
Labels: 💫 Feat
